#          heroku config:add DATABASE_URL=mysql2://kudomind_root:Password12@173.254.28.41:3306/kudomind_jewellery

development:
  adapter: mysql2
#  encoding: utf-8
  pool: 5
  username: "root"
  password: "mysqlz"
  host: "localhost"
  port: "3306"
  database: "jewellery"

production:
  adapter: mysql2
#  encoding: utf-8
  pool: 5
  username: "root"
  password: "q5ktyP0qmX"
  host: "localhost"
  port: "3306"
  database: "jewellery"
